spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #logging.level.org.springframework=debug
    format:
      date: yyyy-MM-dd

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: 2019ugcs001
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none